package swingprj;

import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sridh
 */
public class home extends javax.swing.JFrame {
static void res(JTable tblname,String qry){
    try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");   
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=db_pcoint","sridhar","sridhar");
            String sql=qry;
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet res=pst.executeQuery();
            tblname.setModel(DbUtils.resultSetToTableModel(res));
             }
        catch(Exception ex){
            System.out.println(ex);
        }
}
public void jpan(){
    leftNavEmp.setVisible(false);
}

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        header = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        leftNavall = new javax.swing.JPanel();
        addEmpBtn1 = new javax.swing.JButton();
        empDetailBtn1 = new javax.swing.JButton();
        addEmpBtn2 = new javax.swing.JButton();
        addEmpBtn3 = new javax.swing.JButton();
        userDetailBtn = new javax.swing.JButton();
        leftNavEmp = new javax.swing.JPanel();
        addEmpBtn = new javax.swing.JButton();
        empDetailBtn = new javax.swing.JButton();
        updateEmpBtn = new javax.swing.JButton();
        Backemp = new javax.swing.JButton();
        blank = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        empDetails = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        empDetailstbl = new javax.swing.JTable();
        addEmpCon = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        empID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        others = new javax.swing.JRadioButton();
        AgeFld = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        EmailFld = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        salaryFld = new javax.swing.JTextField();
        AddEmpSub = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        PswFld = new javax.swing.JTextField();
        AddEmpClrBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        NameFld = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        AddphoneNo = new javax.swing.JTextField();
        udEmpCon = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        upEmpId = new javax.swing.JTextField();
        UdFlds = new javax.swing.JComboBox<>();
        UdValFld = new javax.swing.JTextField();
        udBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        uetbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(255, 153, 153));

        logout.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setText("logout");
        logout.setToolTipText("");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jLabel2.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jLabel2.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PCOINT");
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 533, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 60));

        leftNavall.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));

        addEmpBtn1.setBackground(new java.awt.Color(0, 204, 204));
        addEmpBtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addEmpBtn1.setText("Stock update");
        addEmpBtn1.setOpaque(true);
        addEmpBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmpBtn1ActionPerformed(evt);
            }
        });

        empDetailBtn1.setBackground(new java.awt.Color(0, 204, 204));
        empDetailBtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        empDetailBtn1.setText("Employee Details");
        empDetailBtn1.setToolTipText("");
        empDetailBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empDetailBtn1ActionPerformed(evt);
            }
        });

        addEmpBtn2.setBackground(new java.awt.Color(0, 204, 204));
        addEmpBtn2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addEmpBtn2.setText("Price update");
        addEmpBtn2.setOpaque(true);
        addEmpBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmpBtn2ActionPerformed(evt);
            }
        });

        addEmpBtn3.setBackground(new java.awt.Color(0, 204, 204));
        addEmpBtn3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addEmpBtn3.setText("Sell Product");
        addEmpBtn3.setOpaque(true);
        addEmpBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmpBtn3ActionPerformed(evt);
            }
        });

        userDetailBtn.setBackground(new java.awt.Color(0, 204, 204));
        userDetailBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userDetailBtn.setText("User Details");
        userDetailBtn.setOpaque(true);
        userDetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userDetailBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftNavallLayout = new javax.swing.GroupLayout(leftNavall);
        leftNavall.setLayout(leftNavallLayout);
        leftNavallLayout.setHorizontalGroup(
            leftNavallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftNavallLayout.createSequentialGroup()
                .addGroup(leftNavallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftNavallLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(empDetailBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                    .addGroup(leftNavallLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(leftNavallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addEmpBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addEmpBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addEmpBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(leftNavallLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userDetailBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        leftNavallLayout.setVerticalGroup(
            leftNavallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftNavallLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(empDetailBtn1)
                .addGap(8, 8, 8)
                .addComponent(userDetailBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addEmpBtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addEmpBtn2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addEmpBtn3)
                .addContainerGap(317, Short.MAX_VALUE))
        );

        getContentPane().add(leftNavall, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 170, 510));

        leftNavEmp.setBackground(new java.awt.Color(0, 204, 204));

        addEmpBtn.setBackground(new java.awt.Color(0, 204, 204));
        addEmpBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addEmpBtn.setText("Add Employee");
        addEmpBtn.setOpaque(true);
        addEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmpBtnActionPerformed(evt);
            }
        });

        empDetailBtn.setBackground(new java.awt.Color(0, 204, 204));
        empDetailBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        empDetailBtn.setText("Employee Details");
        empDetailBtn.setToolTipText("");
        empDetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empDetailBtnActionPerformed(evt);
            }
        });

        updateEmpBtn.setBackground(new java.awt.Color(0, 204, 204));
        updateEmpBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateEmpBtn.setText("Update Employee");
        updateEmpBtn.setOpaque(true);
        updateEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmpBtnActionPerformed(evt);
            }
        });

        Backemp.setBackground(new java.awt.Color(0, 204, 204));
        Backemp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Backemp.setText("Back");
        Backemp.setOpaque(true);
        Backemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackempActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftNavEmpLayout = new javax.swing.GroupLayout(leftNavEmp);
        leftNavEmp.setLayout(leftNavEmpLayout);
        leftNavEmpLayout.setHorizontalGroup(
            leftNavEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftNavEmpLayout.createSequentialGroup()
                .addGroup(leftNavEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftNavEmpLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(leftNavEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(empDetailBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateEmpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftNavEmpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addEmpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(leftNavEmpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Backemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        leftNavEmpLayout.setVerticalGroup(
            leftNavEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftNavEmpLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(empDetailBtn)
                .addGap(18, 18, 18)
                .addComponent(addEmpBtn)
                .addGap(12, 12, 12)
                .addComponent(updateEmpBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Backemp)
                .addContainerGap(346, Short.MAX_VALUE))
        );

        getContentPane().add(leftNavEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 170, 510));

        blank.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboard.jpg"))); // NOI18N
        jLabel3.setToolTipText("");
        jLabel3.setDoubleBuffered(true);
        blank.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 510));

        getContentPane().add(blank, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 600, 510));

        empDetails.setBackground(new java.awt.Color(153, 255, 204));

        empDetailstbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        empDetailstbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(empDetailstbl);

        javax.swing.GroupLayout empDetailsLayout = new javax.swing.GroupLayout(empDetails);
        empDetails.setLayout(empDetailsLayout);
        empDetailsLayout.setHorizontalGroup(
            empDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empDetailsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        empDetailsLayout.setVerticalGroup(
            empDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empDetailsLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        getContentPane().add(empDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 600, 510));

        addEmpCon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Employee");
        jLabel1.setToolTipText("");
        jLabel1.setOpaque(true);
        addEmpCon.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 138, 35));

        jLabel5.setBackground(new java.awt.Color(255, 204, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("emp ID");
        jLabel5.setOpaque(true);
        addEmpCon.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 90, 30));
        addEmpCon.add(empID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 170, 30));

        jLabel6.setBackground(new java.awt.Color(255, 204, 204));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Gender");
        jLabel6.setMaximumSize(new java.awt.Dimension(38, 20));
        jLabel6.setMinimumSize(new java.awt.Dimension(38, 20));
        jLabel6.setName(""); // NOI18N
        jLabel6.setOpaque(true);
        addEmpCon.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 90, 30));

        jLabel8.setBackground(new java.awt.Color(255, 204, 204));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Age");
        jLabel8.setOpaque(true);
        addEmpCon.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 90, 30));

        gender.add(male);
        male.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        addEmpCon.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 60, 30));

        gender.add(female);
        female.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        female.setText("Female");
        addEmpCon.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, 30));

        gender.add(others);
        others.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        others.setText("Others");
        addEmpCon.add(others, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, 30));
        addEmpCon.add(AgeFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 170, 30));

        jLabel9.setBackground(new java.awt.Color(255, 204, 204));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Email");
        jLabel9.setOpaque(true);
        addEmpCon.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 90, 30));

        EmailFld.setToolTipText("");
        addEmpCon.add(EmailFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 170, 30));

        jLabel10.setBackground(new java.awt.Color(255, 204, 204));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Salary");
        jLabel10.setOpaque(true);
        addEmpCon.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 90, 30));
        addEmpCon.add(salaryFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 170, 30));

        AddEmpSub.setBackground(new java.awt.Color(204, 255, 204));
        AddEmpSub.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddEmpSub.setText("submit");
        AddEmpSub.setToolTipText("");
        AddEmpSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmpSubActionPerformed(evt);
            }
        });
        addEmpCon.add(AddEmpSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 90, 30));

        jLabel11.setBackground(new java.awt.Color(255, 204, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Password");
        jLabel11.setOpaque(true);
        addEmpCon.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 90, 30));
        addEmpCon.add(PswFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 170, 30));

        AddEmpClrBtn.setBackground(new java.awt.Color(255, 51, 51));
        AddEmpClrBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddEmpClrBtn.setText("Clear");
        AddEmpClrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmpClrBtnActionPerformed(evt);
            }
        });
        addEmpCon.add(AddEmpClrBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, -1, 30));

        jLabel14.setBackground(new java.awt.Color(255, 204, 204));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("name");
        jLabel14.setOpaque(true);
        addEmpCon.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 90, 30));
        addEmpCon.add(NameFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 170, 30));

        jLabel15.setBackground(new java.awt.Color(255, 204, 204));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Phone No");
        jLabel15.setOpaque(true);
        addEmpCon.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 90, 30));
        addEmpCon.add(AddphoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 170, 30));

        getContentPane().add(addEmpCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 600, 510));

        jLabel4.setBackground(new java.awt.Color(255, 255, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Update Employee Details");
        jLabel4.setOpaque(true);

        UdFlds.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "name", "email", "phoneNo", "salary", "age", "password" }));
        UdFlds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UdFldsActionPerformed(evt);
            }
        });

        UdValFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UdValFldActionPerformed(evt);
            }
        });

        udBtn.setBackground(new java.awt.Color(153, 255, 153));
        udBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        udBtn.setText("Update");
        udBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                udBtnActionPerformed(evt);
            }
        });

        uetbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "name", "age", "DOB", "password", "email", "salary"
            }
        ));
        jScrollPane2.setViewportView(uetbl);

        javax.swing.GroupLayout udEmpConLayout = new javax.swing.GroupLayout(udEmpCon);
        udEmpCon.setLayout(udEmpConLayout);
        udEmpConLayout.setHorizontalGroup(
            udEmpConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(udEmpConLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(udEmpConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(udEmpConLayout.createSequentialGroup()
                        .addComponent(UdFlds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(UdValFld, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(udEmpConLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(udEmpConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(udEmpConLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(37, Short.MAX_VALUE))
                    .addGroup(udEmpConLayout.createSequentialGroup()
                        .addComponent(upEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(udBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
        );
        udEmpConLayout.setVerticalGroup(
            udEmpConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(udEmpConLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(udEmpConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(udBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(udEmpConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(upEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UdFlds, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UdValFld, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(udEmpCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 600, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        dispose();
        Login lg= new Login();
        lg.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void addEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmpBtnActionPerformed
        blank.setVisible(false);
        udEmpCon.setVisible(false);
        empDetails.setVisible(false);
        addEmpCon.setVisible(true);
    }//GEN-LAST:event_addEmpBtnActionPerformed

    private void empDetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empDetailBtnActionPerformed
        blank.setVisible(false);
        addEmpCon.setVisible(false);
        udEmpCon.setVisible(false);
        empDetails.setVisible(true);
           home.res(empDetailstbl, "exec sp_view");
    }//GEN-LAST:event_empDetailBtnActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        
    }//GEN-LAST:event_maleActionPerformed

    private void AddEmpClrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmpClrBtnActionPerformed
       AgeFld.setText("");
       EmailFld.setText("");
       empID.setText("");
       PswFld.setText("");
       salaryFld.setText("");
       gender.clearSelection();
       NameFld.setText("");
       AddphoneNo.setText("");
    }//GEN-LAST:event_AddEmpClrBtnActionPerformed

    private void updateEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmpBtnActionPerformed
        blank.setVisible(false);
        addEmpCon.setVisible(false);
        empDetails.setVisible(false);
        udEmpCon.setVisible(true);
        home.res(uetbl,"exec sp_view");
    }//GEN-LAST:event_updateEmpBtnActionPerformed

    private void UdValFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UdValFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UdValFldActionPerformed

    private void UdFldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UdFldsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UdFldsActionPerformed

    private void udBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_udBtnActionPerformed
      String empid=upEmpId.getText();
      String udcol=(String) UdFlds.getSelectedItem();
      String upvalue=UdValFld.getText();
      try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");   
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=db_pcoint","sridhar","sridhar");
            if(empid!=null &&udcol!=null&&upvalue!=null){    
            String sql="exec sp_empUpdate ?,?,?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, empid);
            pst.setString(2, udcol);
            pst.setString(3, upvalue);
            int i=pst.executeUpdate();
             if(i>0){
                  JOptionPane.showMessageDialog(null, "Login sucess...", "message box", HEIGHT);
                  home.res(uetbl,"exec sp_view");
                  upEmpId.setText("");
                  UdFlds.setSelectedIndex(0);
                  UdValFld.setText("");
             }
            }
             }
        catch(ClassNotFoundException | SQLException ex){
            System.out.println(ex);
        }
      
    }//GEN-LAST:event_udBtnActionPerformed

    private void AddEmpSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmpSubActionPerformed
        String empname=NameFld.getText();
        String empphoneno=AddphoneNo.getText();
        String empgender = null;
        String empAge=AgeFld.getText();
        String empemail=EmailFld.getText();
        String empSalary=salaryFld.getText();
        String emppsw=PswFld.getText();
        String empid=empID.getText();
        if(female.isSelected()){
            empgender="female";
        }
        else if(male.isSelected()){
            empgender="male";
        }
        else if(others.isSelected()){
            empgender="others";
        }
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");   
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=db_pcoint","sridhar","sridhar");
            if(!"".equals(empgender) && !"".equals(empname) && !"".equals(emppsw)){
            String sql="exec sp_addEmp '"+empid+"','"+empname+"','"+empgender+"','"+empAge+"','"+empphoneno+"','"+empemail+"','"+empSalary+"','"+emppsw+"'";
            PreparedStatement pst = con.prepareStatement(sql);
            int i=pst.executeUpdate();
            if(i>0){
                JOptionPane.showMessageDialog(null, "Add sucess", "message box", HEIGHT);
                AgeFld.setText("");
                EmailFld.setText("");
                empID.setText("");
                PswFld.setText("");
                salaryFld.setText("");
                gender.clearSelection();
                NameFld.setText("");
                AddphoneNo.setText("");
            }
            }
             }
        catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_AddEmpSubActionPerformed

    private void addEmpBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmpBtn1ActionPerformed
        productDetails pd=new productDetails();
        pd.setVisible(true);
    }//GEN-LAST:event_addEmpBtn1ActionPerformed

    private void empDetailBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empDetailBtn1ActionPerformed
        leftNavall.setVisible(false);
        leftNavEmp.setVisible(true);
    }//GEN-LAST:event_empDetailBtn1ActionPerformed

    private void BackempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackempActionPerformed
       leftNavEmp.setVisible(false);
        leftNavall.setVisible(true);
    }//GEN-LAST:event_BackempActionPerformed

    private void addEmpBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmpBtn2ActionPerformed
       ProductPriceUpdate ppu=new ProductPriceUpdate();
        ppu.setVisible(true);
    }//GEN-LAST:event_addEmpBtn2ActionPerformed

    private void addEmpBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmpBtn3ActionPerformed
    SellPrt sp= new SellPrt();
    sp.setVisible(true);
    }//GEN-LAST:event_addEmpBtn3ActionPerformed

    private void userDetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userDetailBtnActionPerformed
        userDetails ud= new userDetails();
        ud.setVisible(true);
    }//GEN-LAST:event_userDetailBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmpClrBtn;
    private javax.swing.JButton AddEmpSub;
    private javax.swing.JTextField AddphoneNo;
    private javax.swing.JTextField AgeFld;
    private javax.swing.JButton Backemp;
    private javax.swing.JTextField EmailFld;
    private javax.swing.JTextField NameFld;
    private javax.swing.JTextField PswFld;
    private javax.swing.JComboBox<String> UdFlds;
    private javax.swing.JTextField UdValFld;
    private javax.swing.JButton addEmpBtn;
    private javax.swing.JButton addEmpBtn1;
    private javax.swing.JButton addEmpBtn2;
    private javax.swing.JButton addEmpBtn3;
    private javax.swing.JPanel addEmpCon;
    private javax.swing.JPanel blank;
    private javax.swing.JButton empDetailBtn;
    private javax.swing.JButton empDetailBtn1;
    private javax.swing.JPanel empDetails;
    private javax.swing.JTable empDetailstbl;
    private javax.swing.JTextField empID;
    private javax.swing.JRadioButton female;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel leftNavEmp;
    private javax.swing.JPanel leftNavall;
    private javax.swing.JButton logout;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton others;
    private javax.swing.JTextField salaryFld;
    private javax.swing.JButton udBtn;
    private javax.swing.JPanel udEmpCon;
    private javax.swing.JTable uetbl;
    private javax.swing.JTextField upEmpId;
    private javax.swing.JButton updateEmpBtn;
    private javax.swing.JButton userDetailBtn;
    // End of variables declaration//GEN-END:variables
}
