package swingprj;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sridh
 */
public class NewUser extends javax.swing.JFrame {

    /**
     * Creates new form NewUser
     */
    public NewUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nuname = new javax.swing.JTextField();
        UAge = new javax.swing.JTextField();
        UEmail = new javax.swing.JTextField();
        UPhno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        EmpId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        UTotalPrtQun = new javax.swing.JLabel();
        UTotalPrtPrice = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(740, 510));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USER FORM");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 40, 190, 38));

        nuname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nuname.setVerifyInputWhenFocusTarget(false);
        nuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nunameActionPerformed(evt);
            }
        });
        getContentPane().add(nuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 200, 25));

        UAge.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(UAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 200, 25));

        UEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(UEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 200, 25));

        UPhno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(UPhno, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 200, 25));

        jLabel2.setBackground(java.awt.Color.orange);
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Cus Name");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 120, 25));

        jLabel3.setBackground(java.awt.Color.orange);
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Age");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 120, 25));

        jLabel4.setBackground(java.awt.Color.orange);
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Email");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 120, 25));

        jLabel5.setBackground(java.awt.Color.orange);
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Phone NO");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 120, 25));

        submit.setBackground(java.awt.Color.green);
        submit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        submit.setText("submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 100, 35));

        exit.setBackground(java.awt.Color.green);
        exit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        exit.setText("exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 100, 35));

        jLabel6.setBackground(java.awt.Color.orange);
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Emp Id");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 120, 25));
        getContentPane().add(EmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 200, 25));

        jLabel7.setBackground(java.awt.Color.orange);
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Total Prt Qun");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 120, 25));

        UTotalPrtQun.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UTotalPrtQun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UTotalPrtQun.setOpaque(true);
        getContentPane().add(UTotalPrtQun, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 200, 25));

        UTotalPrtPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UTotalPrtPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UTotalPrtPrice.setOpaque(true);
        getContentPane().add(UTotalPrtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 200, 25));

        jLabel8.setBackground(java.awt.Color.orange);
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Total Prt Price");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 120, 25));

        jLabel9.setBackground(new java.awt.Color(51, 153, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(102, 255, 0)));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 400, 450));

        jLabel10.setBackground(new java.awt.Color(0, 204, 204));
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nunameActionPerformed
    
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        String empId=EmpId.getText();
        String uname=nuname.getText();
        String nupass=UAge.getText();
        String nuemail=UEmail.getText();
        String nuphno=UPhno.getText();
        String qun=UTotalPrtQun.getText();
        String price=UTotalPrtPrice.getText();
        if(uname.equals("")){
            JOptionPane.showMessageDialog(null, "enter user name", "fill column", HEIGHT);
        }
        else if(nupass.equals("")){
            JOptionPane.showMessageDialog(null, "enter password", "fill column", HEIGHT);
        }
        else if(nuemail.equals("")){
            JOptionPane.showMessageDialog(null, "enter email", "fill column", HEIGHT);
        }
        else if(nuphno.equals("")){
            JOptionPane.showMessageDialog(null, "enter phone no", "fill column", HEIGHT);
        }
        else{
            try{
                String sql = "exec sp_sellPrt '"+empId+"','"+uname+"','"+nupass+"','"+nuemail+"','"+nuphno+"','"+qun+"','"+price+"'";
                productDetails.Update(sql);
                dispose();
        }
        catch(Exception e){
            System.out.println(e);
        }
        }
        
    }//GEN-LAST:event_submitActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmpId;
    private javax.swing.JTextField UAge;
    private javax.swing.JTextField UEmail;
    private javax.swing.JTextField UPhno;
    public javax.swing.JLabel UTotalPrtPrice;
    public javax.swing.JLabel UTotalPrtQun;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nuname;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
