/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swingprj;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author sridh
 */
public class userDetails extends javax.swing.JFrame {

    /**
     * Creates new form userDetails
     */
    public userDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftNavEmp = new javax.swing.JPanel();
        empDetailBtn = new javax.swing.JButton();
        updateEmpBtn = new javax.swing.JButton();
        Backemp = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        empDetails = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        empDetailstbl = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        udEmpCon = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        upUserId = new javax.swing.JTextField();
        UdFlds = new javax.swing.JComboBox<>();
        UdValFld = new javax.swing.JTextField();
        udBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        uetbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftNavEmp.setBackground(new java.awt.Color(0, 204, 204));

        empDetailBtn.setBackground(new java.awt.Color(0, 204, 204));
        empDetailBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        empDetailBtn.setText("User Details");
        empDetailBtn.setToolTipText("");
        empDetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empDetailBtnActionPerformed(evt);
            }
        });

        updateEmpBtn.setBackground(new java.awt.Color(0, 204, 204));
        updateEmpBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateEmpBtn.setText("Update User");
        updateEmpBtn.setOpaque(true);
        updateEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmpBtnActionPerformed(evt);
            }
        });

        Backemp.setBackground(new java.awt.Color(0, 204, 204));
        Backemp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Backemp.setText("Back");
        Backemp.setOpaque(true);
        Backemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackempActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftNavEmpLayout = new javax.swing.GroupLayout(leftNavEmp);
        leftNavEmp.setLayout(leftNavEmpLayout);
        leftNavEmpLayout.setHorizontalGroup(
            leftNavEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftNavEmpLayout.createSequentialGroup()
                .addGroup(leftNavEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftNavEmpLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(empDetailBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftNavEmpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(updateEmpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                    .addComponent(Backemp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        leftNavEmpLayout.setVerticalGroup(
            leftNavEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftNavEmpLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(empDetailBtn)
                .addGap(18, 18, 18)
                .addComponent(updateEmpBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Backemp)
                .addContainerGap(385, Short.MAX_VALUE))
        );

        getContentPane().add(leftNavEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 170, 510));

        header.setBackground(new java.awt.Color(255, 153, 153));

        logout.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setText("logout");
        logout.setToolTipText("");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jLabel2.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jLabel2.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PCOINT");
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 533, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 60));

        empDetails.setBackground(new java.awt.Color(153, 255, 204));

        empDetailstbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        empDetailstbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(empDetailstbl);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboard.jpg"))); // NOI18N

        javax.swing.GroupLayout empDetailsLayout = new javax.swing.GroupLayout(empDetails);
        empDetails.setLayout(empDetailsLayout);
        empDetailsLayout.setHorizontalGroup(
            empDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empDetailsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(empDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(empDetailsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        empDetailsLayout.setVerticalGroup(
            empDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empDetailsLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(empDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(empDetailsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(empDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 600, 510));

        udEmpCon.setBackground(new java.awt.Color(102, 255, 204));
        udEmpCon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Update Employee Details");
        jLabel4.setOpaque(true);
        udEmpCon.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 25, -1, 31));

        upUserId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        upUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upUserIdActionPerformed(evt);
            }
        });
        udEmpCon.add(upUserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 74, 89, 32));

        UdFlds.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UdFlds.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "name", "email", "phoneNo", "age" }));
        UdFlds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UdFldsActionPerformed(evt);
            }
        });
        udEmpCon.add(UdFlds, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 74, -1, 32));

        UdValFld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UdValFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UdValFldActionPerformed(evt);
            }
        });
        udEmpCon.add(UdValFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 74, 97, 32));

        udBtn.setBackground(new java.awt.Color(153, 255, 153));
        udBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        udBtn.setText("Update");
        udBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                udBtnActionPerformed(evt);
            }
        });
        udEmpCon.add(udBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 74, 81, 32));

        uetbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "name", "age", "DOB", "password", "email", "salary"
            }
        ));
        jScrollPane2.setViewportView(uetbl);

        udEmpCon.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 124, 522, 340));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboard.jpg"))); // NOI18N
        udEmpCon.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 510));

        getContentPane().add(udEmpCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 600, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UdFldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UdFldsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UdFldsActionPerformed

    private void UdValFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UdValFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UdValFldActionPerformed

    private void udBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_udBtnActionPerformed
        String empid=upUserId.getText();
        String udcol=(String) UdFlds.getSelectedItem();
        String upvalue=UdValFld.getText();
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=db_pcoint","sridhar","sridhar");
            if(empid!=null &&udcol!=null&&upvalue!=null){
                String sql="exec sp_UserUpdate ?,?,?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, empid);
                pst.setString(2, udcol);
                pst.setString(3, upvalue);
                int i=pst.executeUpdate();
                if(i>0){
                    JOptionPane.showMessageDialog(null, "Login sucess...", "message box", HEIGHT);
                    home.res(uetbl,"exec sp_UserDetails");
                    upUserId.setText("");
                    UdFlds.setSelectedIndex(0);
                    UdValFld.setText("");
                }
            }
        }
        catch(ClassNotFoundException | SQLException ex){
            System.out.println(ex);
        }

    }//GEN-LAST:event_udBtnActionPerformed

    private void empDetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empDetailBtnActionPerformed
       udEmpCon.setVisible(false);
        empDetails.setVisible(true);
        home.res(empDetailstbl, "exec sp_UserDetails1");
    }//GEN-LAST:event_empDetailBtnActionPerformed

    private void updateEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmpBtnActionPerformed
        empDetails.setVisible(false);
        udEmpCon.setVisible(true);
        home.res(uetbl,"exec sp_UserDetails");
    }//GEN-LAST:event_updateEmpBtnActionPerformed

    private void BackempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackempActionPerformed
        dispose();
        EmployeeDb edb=new EmployeeDb();
        edb.setVisible(true);
    }//GEN-LAST:event_BackempActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        dispose();
        Login lg= new Login();
        lg.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void upUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upUserIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backemp;
    private javax.swing.JComboBox<String> UdFlds;
    private javax.swing.JTextField UdValFld;
    private javax.swing.JButton empDetailBtn;
    private javax.swing.JPanel empDetails;
    private javax.swing.JTable empDetailstbl;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel leftNavEmp;
    private javax.swing.JButton logout;
    private javax.swing.JButton udBtn;
    private javax.swing.JPanel udEmpCon;
    private javax.swing.JTable uetbl;
    private javax.swing.JTextField upUserId;
    private javax.swing.JButton updateEmpBtn;
    // End of variables declaration//GEN-END:variables
}
